//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace beat_on_jeans_escritorio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Generos_Usuarios
    {
        public int ID { get; set; }
        public Nullable<int> Genero_Id { get; set; }
        public Nullable<int> Usuario_Id { get; set; }
    
        public virtual Generos_Musicales Generos_Musicales { get; set; }
        public virtual UsuarioMobil UsuarioMobil { get; set; }
    }
}
