//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace beat_on_jeans_escritorio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mensajes
    {
        public int ID { get; set; }
        public Nullable<int> Chat_ID { get; set; }
        public Nullable<int> Emisor_ID { get; set; }
        public Nullable<System.DateTime> Hora { get; set; }
        public string Mensaje { get; set; }
    
        public virtual Chats Chats { get; set; }
    }
}
