//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace beat_on_jeans_escritorio.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dam05Entities : DbContext
    {
        public dam05Entities()
            : base("name=dam05Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actuacion> Actuacion { get; set; }
        public virtual DbSet<Chats> Chats { get; set; }
        public virtual DbSet<Generos_Musicales> Generos_Musicales { get; set; }
        public virtual DbSet<Generos_Usuarios> Generos_Usuarios { get; set; }
        public virtual DbSet<Locales> Locales { get; set; }
        public virtual DbSet<Matches> Matches { get; set; }
        public virtual DbSet<Mensajes> Mensajes { get; set; }
        public virtual DbSet<Musicos> Musicos { get; set; }
        public virtual DbSet<Notificaciones> Notificaciones { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Soporte> Soporte { get; set; }
        public virtual DbSet<TipoIncidencia> TipoIncidencia { get; set; }
        public virtual DbSet<UsuarioMobil> UsuarioMobil { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<UsuariosCSharp> UsuariosCSharp { get; set; }
        public virtual DbSet<Valoracion> Valoracion { get; set; }
    }
}
