//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace beat_on_jeans_escritorio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Soporte
    {
        public int ID { get; set; }
        public Nullable<int> Usuario_ID { get; set; }
        public Nullable<int> Tecnico_ID { get; set; }
        public Nullable<int> Tipo_Incidencia_ID { get; set; }
        public System.DateTime Fecha_Creacion { get; set; }
        public Nullable<System.DateTime> Fecha_Cierre { get; set; }
    
        public virtual TipoIncidencia TipoIncidencia { get; set; }
        public virtual UsuarioMobil UsuarioMobil { get; set; }
        public virtual UsuariosCSharp UsuariosCSharp { get; set; }
        public virtual UsuarioMobil UsuarioMobil1 { get; set; }
        public virtual UsuariosCSharp UsuariosCSharp1 { get; set; }
    }
}
