//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace beat_on_jeans_escritorio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioMobil
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UsuarioMobil()
        {
            this.Generos_Usuarios = new HashSet<Generos_Usuarios>();
            this.Locales = new HashSet<Locales>();
            this.Musicos = new HashSet<Musicos>();
            this.Soporte = new HashSet<Soporte>();
            this.Soporte1 = new HashSet<Soporte>();
            this.Valoracion = new HashSet<Valoracion>();
            this.Valoracion1 = new HashSet<Valoracion>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Notificacion_ID { get; set; }
        public Nullable<int> ROL_ID { get; set; }
        public string Url_Imagen { get; set; }
        public Nullable<int> Usuario_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Generos_Usuarios> Generos_Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Locales> Locales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Musicos> Musicos { get; set; }
        public virtual Notificaciones Notificaciones { get; set; }
        public virtual Roles Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Soporte> Soporte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Soporte> Soporte1 { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Valoracion> Valoracion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Valoracion> Valoracion1 { get; set; }
    }
}
