//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace beat_on_jeans_escritorio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Valoracion
    {
        public int ID { get; set; }
        public Nullable<int> Valor { get; set; }
        public Nullable<int> Valorado_ID { get; set; }
        public Nullable<int> Valorador_ID { get; set; }
        public string Tipo_Valorado { get; set; }
        public string Tipo_Valorador { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
    
        public virtual Locales Locales { get; set; }
        public virtual Locales Locales1 { get; set; }
        public virtual Musicos Musicos { get; set; }
        public virtual Musicos Musicos1 { get; set; }
    }
}
